apiVersion: v1
kind: Pod
metadata:
 name: logme
 namespace: {{ .Release.Namespace }}
spec:
 containers:
 - name: gen
   image: centos:7
   command:
     - "bin/bash"
     - "-c"
     - |
         while true; do echo "1|$(date "+%Y-%m-%dT%T.%6NZ")||testpackage.testmodule.TestDevice.test_fn|test.py#1    |INFO    |is-tango:yes,devicename:testDevice| Regular information should be logged like this FYI" | tee /dev/stderr; sleep 1; done