{{ if .Values.ingress.enabled }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elastic-ing-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: elastic
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ tpl .Values.ingress.hostname . }}
    http:
      paths:
      - path: /elastic
        backend:
          serviceName: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
          servicePort: 9200
{{ end }}
