{{ if .Values.elastic.enabled }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elastic-curator-{{ template "logging.name" . }}-{{ .Release.Name }}
  labels:
    app: elastic
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: python:3.6-alpine
            name: elastic-curator-{{ template "logging.name" . }}-{{ .Release.Name }}
            args: ["sh", "-c", "pip install elasticsearch-curator && curator_cli --host  http://elastic-{{ template "logging.name" . }}-{{ .Release.Name }} --port 9200 delete_indices --filter_list '[{\"filtertype\":\"age\",\"source\":\"creation_date\",\"direction\":\"older\",\"unit\":\"days\",\"unit_count\":2}]' || true"]
          restartPolicy: Never

{{ end }}