apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  ska.conf: |
    <filter docker.systemd>
      @type kubernetes_metadata
      use_journal true
    </filter>

    <match kubelet>
      @type null
    </match>

    <match bootkube>
      @type null
    </match>
