{{ if .Values.fluentd.enabled }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: fluentd-{{ template "logging.name" . }}-{{ .Release.Name }}
  labels:
    service: fluentd
spec:
  type: NodePort
  selector:
    run: fluentd
  ports:
  - port: 24224
    targetPort: 24224

{{ end }}
