{{ if .Values.kibana.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: kibana-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: kibana-{{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    run: kibana-{{ .Release.Namespace }}
  ports:
  - port: 5601
    targetPort: 5601

{{ end }}
