# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
rbac:
  enabled: true

namespaces: 
  - name: integration
    users: ["https://gitlab.com#3003086"]
  - name: staging
    users: ["https://gitlab.com#3003086"]
  - name: sarao
    users: ["https://gitlab.com#3003086"]
  - name: ncra
    users: ["https://gitlab.com#3003086"]

nodeSelector: {}

tolerations: []

affinity: {}
