---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rsyslog-{{ template "cbf-proto.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rsyslog-{{ template "cbf-proto.name" . }}-{{ .Release.Name }}
    chart: {{ template "cbf-proto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rsyslog-{{ template "cbf-proto.name" . }}-{{ .Release.Name }}/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsyslog-{{ template "cbf-proto.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rsyslog-{{ template "cbf-proto.name" . }}-{{ .Release.Name }}
    chart: {{ template "cbf-proto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
