image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

stages:
  - lint
  - clean
  - deploy
  - test
  - lifecycle

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

delete test environment:
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=sarao HELM_RELEASE=sarao
  - kubectl delete namespace sarao
  environment:
    name: test
  only:
    variables:
      - $DELETE == "true"

deploy test environment:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all KUBE_NAMESPACE=sarao INGRESS_HOST=sarao.engageska-portugal.pt HELM_RELEASE=sarao
  - kubectl get all,pv,pvc,ingress -n sarao
  retry: 2
  environment:
    name: test

k8s_test test environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:
  - make k8s_test KUBE_NAMESPACE=sarao INGRESS_HOST=sarao.engageska-portugal.pt HELM_RELEASE=sarao && [ -f "build/report.xml" ]
  environment:
    name: test
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml

delete-and-deploy test environment:
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=sarao HELM_RELEASE=sarao
  - make deploy_all KUBE_NAMESPACE=sarao INGRESS_HOST=sarao.engageska-portugal.pt HELM_RELEASE=sarao
  environment:
    name: test
  when: manual
