image: nexus.engageska-portugal.pt/ska-docker/deploy:0.4.3

variables:
  MINIKUBE: "false"
  VALUES: "pipeline.yaml"

stages:
  - clean
  - test
  - post_test
  - debug
  - publish
  - release
  - clean_staging
  - deploy_staging

.uninstall_template: &uninstall_definition
  tags:
  - k8srunner
  script:
  - &uninstall_scripts |
    make uninstall
    kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
    kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
    make delete_namespace
    make delete_sdp_namespace
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

.uninstall_template_after_script: &uninstall_definition_after_script
  after_script:
  - *uninstall_scripts

uninstall mid:
  stage: clean
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
  <<: *uninstall_definition
  environment:
    name: "test"

uninstall low:
  stage: clean
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
  <<: *uninstall_definition
  environment:
    name: "test-low"

.test_template: &test_definition
  tags:
  - k8srunner
  script:
  - make install-or-upgrade
  - make smoketest
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  - make k8s_test && [ -f "build/report.xml" ]
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

test mid:
  stage: test
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
    INGRESS_HOST: "mid.integration.engageska-portugal.pt"
    MARK: "skamid or common"
  <<: *test_definition
  environment:
    name: "test"
    url: "http://mid.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master

test mid on demand:
  stage: test
  variables:
    DEPLOYMENT_CONFIGURATION: "skamid"
    MARK: "skamid or common"
    HELM_RELEASE: "test-mid-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
    INGRESS_HOST: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt"
  <<: *test_definition
  <<: *uninstall_definition_after_script
  environment:
    name: "test"
    url: "http://ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
  when: manual
  only:
    refs:
      - branches

test low:
  stage: test
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
    INGRESS_HOST: "low.integration.engageska-portugal.pt"
    MARK: "skalow or common"
  <<: *test_definition
  environment:
    name: "test-low"
    url: "http://low.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master

test low on demand:
  stage: test
  variables:
    DEPLOYMENT_CONFIGURATION: "skalow"
    MARK: "skalow or common"
    HELM_RELEASE: "test-low-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
    INGRESS_HOST: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt"
  <<: *test_definition
  <<: *uninstall_definition_after_script
  environment:
    name: "test-low"
    url: "http://ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
  when: manual
  only:
    refs:
      - branches

.sdp_config_dump_template: &sdp_config_dump_definition
  tags:
  - docker-executor
  script:
  - kubectl exec -n $KUBE_NAMESPACE sdp-console-0 -- sdpcfg ls values -R / > sdp.config.json
  when: manual
  artifacts:
    paths:
    - sdp.config.json

sdp_config_dump_mid:
  stage: debug
  variables:
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
  environment:
    name: "test"
    url: "http://mid.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master
  <<: *sdp_config_dump_definition

tag_commit:
  stage: release
  tags:
    - k8srunner
  when:
    manual
  needs:
    - job: publish-chart
  only:
    refs:
      - master
  script:
    - make create-publish-tag USERNAME=$GITLAB_USER_NAME EMAILID=$GITLAB_USER_EMAIL # Publish tag on gitlab


clean_staging_low:
  stage: clean_staging
  variables:
    HELM_RELEASE: "staging-low"
    KUBE_NAMESPACE: "staging-low"
    KUBE_NAMESPACE_SDP: "staging-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
  tags:
    - k8srunner
  only:
    refs:
      - tags
  script:
  - *uninstall_scripts
  environment:
    name: "staging-low"
  needs:
    - job: publish-chart

clean_staging_mid:
  stage: clean_staging
  variables:
    HELM_RELEASE: "staging-mid"
    KUBE_NAMESPACE: "staging-mid"
    KUBE_NAMESPACE_SDP: "staging-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
  tags:
    - k8srunner
  only:
    refs:
      - tags
  script:
  - *uninstall_scripts
  environment:
    name: "staging-mid"
  needs:
    - job: publish-chart

deploy_staging_low:
  stage: deploy_staging
  variables:
    HELM_RELEASE: "staging-low"
    KUBE_NAMESPACE: "staging-low"
    KUBE_NAMESPACE_SDP: "staging-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
    INGRESS_HOST: "low.staging.engageska-portugal.pt"
  environment:
    name: "staging-low"
    url: "http://low.staging.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  tags:
    - k8srunner
  script:
    - make install-or-upgrade
    - make smoketest
    - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  only:
    refs:
      - tags
  
deploy_staging_mid:
  stage: deploy_staging
  variables:
    HELM_RELEASE: "staging-mid"
    KUBE_NAMESPACE: "staging-mid"
    KUBE_NAMESPACE_SDP: "staging-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
    INGRESS_HOST: "mid.staging.engageska-portugal.pt"
  environment:
    name: "staging-mid"
    url: "http://mid.staging.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  tags:
    - k8srunner
  script:
    - make install-or-upgrade
    - make smoketest
    - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  only:
    refs:
      - tags

xray_report:
  stage: post_test
  tags:
  - docker-executor
  script:
    - 'curl -X POST -H "Content-type: application/json" --fail
         -H "Authorization: Basic $JIRA_AUTH"
         --data @build/cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  when: always
  only: [master]
  retry: 2


variables:
  CHARTS_TO_PUBLISH: ska-low ska-mid
include:
# Helm Chart Publish
# https://developer.skatelescope.org/en/latest/development/software_package_release_procedure.html#package-and-publish-helm-charts-to-the-ska-helm-chart-repository
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/helm_publish.yml'

