image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

before_script:
  - helm init --client-only

stages:
  - lint
  - clean
  - deploy
  - test
  - lifecycle
  - debug

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

delete test environment:
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=ncra HELM_RELEASE=ncra INGRESS_HOST=ncra.engageska-portugal.pt
  - kubectl delete namespace ncra
  environment:
    name: test

deploy test environment:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all KUBE_NAMESPACE=ncra HELM_RELEASE=ncra INGRESS_HOST=ncra.engageska-portugal.pt
  - kubectl get all,pv,pvc,ingress -n ncra
  retry: 2
  environment:
    name: test

k8s_test test environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:
  - make k8s_test KUBE_NAMESPACE=ncra HELM_RELEASE=ncra INGRESS_HOST=ncra.engageska-portugal.pt && [ -f "build/report.xml" ]
  environment:
    name: test
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml

print-debug-info:
  stage: debug
  variables:
    KUBE_NAMESPACE: ncra
  tags:
  - docker-executor
  script:
  - kubectl describe ingresses --all-namespaces
  - kubectl describe -n kube-system pod $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1)
  - kubectl logs --tail=100 -n kube-system  $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1)
  - make podlogs KUBE_NAMESPACE=$KUBE_NAMESPACE
  - kubectl logs --tail=100 -n $KUBE_NAMESPACE $(kubectl get pod -n $KUBE_NAMESPACE | grep fluentd | head -n 1  | cut -d\  -f1)
  - kubectl get all --all-namespaces
  environment:
    name: test
  when: manual
  allow_failure: true
