image: ubuntu:18.04

cache:
  paths: 
    - ansible-playbooks/

before_script:
    - apt-get update
    - apt-get install -y bash python apt-transport-https ca-certificates curl software-properties-common
    - apt-add-repository --yes --update ppa:ansible/ansible 
    - apt-get -y install ansible git ssh

stages:
  - download 
  - deploy

download:
  stage: download
  tags: 
  - docker-executor
  script:
  - rm -f ansible-playbook
  - git clone https://github.com/ska-telescope/ansible-playbooks.git
  - cd ansible-playbooks
  - echo -e "\n\n[integration]" >> hosts
  - echo "$ENVIRONMENT_ADDRESS  ansible_user=$ENVIRONMENT_USER" >> hosts
  - cat hosts
  

deploy:
  stage: deploy
  tags:
  - docker-executor
  script:  
  - cd ansible-playbooks
  - mkdir -p /root/.ssh
  - echo "$CONTAINER_PRIVATE_KEY" >> /root/.ssh/id_rsa
  - echo "$CONTAINER_PUBLIC_KEY" >> /root/.ssh/id_rsa.pub
  - chmod 400 /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
  - ssh -o StrictHostKeyChecking=no $ENVIRONMENT_USER@$ENVIRONMENT_ADDRESS date
  - ansible-playbook -vvv -i hosts -u $ENVIRONMENT_USER deploy_integrationenv.yml

stop_namespace_and_deploy:
  stage: deploy 
  tags:
  - docker-executor
  script: 
  - cd ansible-playbooks
  - mkdir -p /root/.ssh
  - echo "$CONTAINER_PRIVATE_KEY" >> /root/.ssh/id_rsa
  - echo "$CONTAINER_PUBLIC_KEY" >> /root/.ssh/id_rsa.pub
  - chmod 400 /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
  - ssh -o StrictHostKeyChecking=no $ENVIRONMENT_USER@$ENVIRONMENT_ADDRESS date
  - ansible-playbook -vvv -i hosts -u $ENVIRONMENT_USER deploy_integrationenv.yml --extra-vars "stop_integrated_system='yes'"
  when: manual

remove_cluster_and_deploy:
  stage: deploy
  tags:
  - docker-executor
  script: 
  - cd ansible-playbooks
  - mkdir -p /root/.ssh
  - echo "$CONTAINER_PRIVATE_KEY" >> /root/.ssh/id_rsa
  - echo "$CONTAINER_PUBLIC_KEY" >> /root/.ssh/id_rsa.pub
  - chmod 400 /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
  - ssh -o StrictHostKeyChecking=no $ENVIRONMENT_USER@$ENVIRONMENT_ADDRESS date
  - ansible-playbook -vvv -i hosts -u $ENVIRONMENT_USER deploy_integrationenv.yml --extra-vars "remove_cluster='yes'"
  when: manual