#
# Note: Tests can be run locally with
#   gitlab-runner exec <executor, eg. docker> <job name>
#

cache:
  paths:
    - build

stages:
  - publish
  - release
  - docs

tag_commit:
  stage: release
  tags:
    - k8srunner
  when:
    manual
  needs:
    - job: publish-chart
  only:
    refs:
      - master
  script:
    # - echo $GITLAB_USER_EMAIL
    - make create-publish-tag USERNAME=$GITLAB_USER_NAME EMAILID=$GITLAB_USER_EMAIL # Publish tag on gitlab

#
# variables:
#   CHARTS_TO_PUBLISH: tea

include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm_publish.yml'

  # Create Gitlab CI badges from CI metrics
  # https://developer.skatelescope.org/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'
