image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

stages:
  - lint
  - clean
  - deploy
  - test
  - lifecycle

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

delete test environment:
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=ncra HELM_RELEASE=ncra
  - kubectl delete namespace ncra
  environment:
    name: test
  only:
    variables:
      - $DELETE == "true"

deploy test environment:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all KUBE_NAMESPACE=ncra INGRESS_HOST=ncra.engageska-portugal.pt HELM_RELEASE=ncra
  - kubectl get all,pv,pvc,ingress -n ncra
  retry: 2
  environment:
    name: test

k8s_test test environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:
  - make k8s_test KUBE_NAMESPACE=ncra INGRESS_HOST=ncra.engageska-portugal.pt HELM_RELEASE=ncra && [ -f "build/report.xml" ]
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml

smoketest test environment:
  stage: test
  tags:
  - docker-executor
  script:
  - ./scripts/smoketest.sh
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  only:
    refs:
      - master

k8s_test staging environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:  
  - make k8s_test KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt HELM_RELEASE=staging && [ -f "build/report.xml" ]
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  only:
    refs:
      - staging
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml

delete-and-deploy test environment:
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=ncra HELM_RELEASE=ncra
  - make deploy_all KUBE_NAMESPACE=ncra INGRESS_HOST=ncra.engageska-portugal.pt HELM_RELEASE=ncra
  environment:
    name: test
  when: manual
