image: ubuntu:18.04

before_script:
    - apt-get update
    - apt-get install -y bash python apt-transport-https ca-certificates curl software-properties-common

deploy_on_integration_enviroment:
  tags:
  - docker-executor
  script:  
  - apt-add-repository --yes --update ppa:ansible/ansible 
  - apt-get -y install ansible git ssh
  - git clone https://github.com/ska-telescope/ansible-playbooks.git
  - cd ansible-playbooks
  - echo -e "\n\n[integration]" >> hosts
  - echo "$ENVIRONMENT_ADDRESS  ansible_user=$ENVIRONMENT_USER" >> hosts
  - cat hosts
  - mkdir -p /home/ubuntu/.ssh
  - echo "$CONTAINER_PRIVATE_KEY" >> /home/ubuntu/.ssh/id_rsa
  - echo "$CONTAINER_PUBLIC_KEY" >> /home/ubuntu/.ssh/id_rsa.pub
  - chmod 400 /home/ubuntu/.ssh/id_rsa /home/ubuntu/.ssh/id_rsa.pub
  - ssh -o StrictHostKeyChecking=no $ENVIRONMENT_USER@$ENVIRONMENT_ADDRESS date
  - ansible-playbook -vvv -i hosts deploy_integrationenv.yml
