image: nexus.engageska-portugal.pt/ska-docker/deploy:0.4.3

variables:
  MINIKUBE: "false"
  VALUE: "pipeline.yaml"

stages:
  - clean
  - test
  - post_test
  - debug

uninstall mid:
  stage: clean
  variables:
    KUBE_NAMESPACE: "integration"
    KUBE_NAMESPACE_SDP: "integration-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
  tags:
  - docker-executor
  script:
  - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - make uninstall
  environment:
    name: "test"
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

uninstall mid on demand:
  stage: clean
  variables:
    DEPLOYMENT_CONFIGURATION: "skamid"
    HELM_RELEASE: "test-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
  tags:
  - docker-executor
  script:
  - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - make uninstall
  environment:
    name: "test"
  when: manual
  only:
    refs:
      - branches

uninstall low:
  stage: clean
  variables:
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-sdp-low"
    DEPLOYMENT_CONFIGURATION: "skalow"
  tags:
    - docker-executor
  script:
  - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - make uninstall
  environment:
    name: "test-low"
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

uninstall low on demand:
  stage: clean
  variables:
    HELM_RELEASE: "test-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
  tags:
    - docker-executor
  script:
  - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - make uninstall
  environment:
    name: "test-low"
    url: "http://low.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  when: manual
  only:
    refs:
      - branches

test mid:
  stage: test
  variables:
    KUBE_NAMESPACE: "integration"
    KUBE_NAMESPACE_SDP: "integration-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
    INGRESS_HOST: "integration.engageska-portugal.pt"
    MARK: "skamid or common"
  tags:
  - docker-executor
  script:
  - make install-or-upgrade
  - make smoketest
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  - make k8s_test && [ -f "build/report.xml" ]
  environment:
    name: "test"
    url: "http://integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

test mid on demand:
  stage: test
  variables:
    DEPLOYMENT_CONFIGURATION: "skamid"
    MARK: "skamid or common"
    HELM_RELEASE: "test-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
    INGRESS_HOST: "ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt"
  tags:
  - docker-executor
  script:
  - make install-or-upgrade
  - make smoketest
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  - make k8s_test && [ -f "build/report.xml" ]
  environment:
    name: "test"
    url: "http://ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  when: manual
  only:
    refs:
      - branches
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

test low:
  stage: test
  variables:
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
    INGRESS_HOST: "low.integration.engageska-portugal.pt"
    MARK: "skalow or common"
  tags:
  - docker-executor
  script:
  - make install-or-upgrade
  - make smoketest
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  - make k8s_test && [ -f "build/report.xml" ]
  environment:
    name: "test-low"
    url: "http://low.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

test low on demand:
  stage: test
  variables:
    DEPLOYMENT_CONFIGURATION: "skalow"
    MARK: "skalow or common"
    HELM_RELEASE: "test-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
    INGRESS_HOST: "ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.low.integration.engageska-portugal.pt"
  tags:
  - docker-executor
  script:
  - make install-or-upgrade
  - make smoketest
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  - make k8s_test && [ -f "build/report.xml" ]
  environment:
    name: "test-low"
    url: "http://ci-test-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.low.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  when: manual
  only:
    refs:
      - branches
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

sdp_config_dump:
  stage: debug
  variables:
    KUBE_NAMESPACE: "integration"
    KUBE_NAMESPACE_SDP: "integration-sdp"
    DEPLOY_ENVIRONMENT: "test"
  only:
    refs:
      - master
  tags:
  - docker-executor
  script:
  - kubectl exec -n $KUBE_NAMESPACE sdp-console-0 -- sdpcfg ls values -R / > sdp.config.json
  environment:
    name: $DEPLOY_ENVIRONMENT
    kubernetes:
      namespace: $KUBE_NAMESPACE
  when: manual
  artifacts:
    paths:
    - sdp.config.json

xray_report:
  stage: post_test
  tags:
  - docker-executor
  script:
    - 'curl -X POST -H "Content-type: application/json" --fail
         -H "Authorization: Basic $JIRA_AUTH"
         --data @build/cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  when: always
  only: [master]
  retry: 2
