image: nexus.engageska-portugal.pt/ska-docker/deploy:0.4.3

variables:
  MINIKUBE: "false"
  VALUES: "pipeline.yaml"

stages:
  - clean
  - test
  - post_test
  - debug

.uninstall_template: &uninstall_definition
  tags:
  - docker-executor
  script:
  - make uninstall
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

uninstall mid:
  stage: clean
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
  <<: *uninstall_definition
  environment:
    name: "test"

uninstall low:
  stage: clean
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
  <<: *uninstall_definition
  environment:
    name: "test-low"

.test_template: &test_definition
  tags:
  - docker-executor
  script:
  - make install-or-upgrade
  - make smoketest
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  - make k8s_test && [ -f "build/report.xml" ]
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

test mid:
  stage: test
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "skamid"
    INGRESS_HOST: "mid.integration.engageska-portugal.pt"
    MARK: "skamid or common"
  <<: *test_definition
  environment:
    name: "test"
    url: "http://mid.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master

test mid on demand:
  stage: test
  variables:
    DEPLOYMENT_CONFIGURATION: "skamid"
    MARK: "skamid or common"
    HELM_RELEASE: "test-mid-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
    INGRESS_HOST: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt"
  <<: *test_definition
  after_script:
  - make uninstall
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - make delete_namespace
  - make delete_sdp_namespace
  environment:
    name: "test"
    url: "http://ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: "ci-test-mid-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
  when: manual
  only:
    refs:
      - branches

test low:
  stage: test
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "skalow"
    INGRESS_HOST: "low.integration.engageska-portugal.pt"
    MARK: "skalow or common"
  <<: *test_definition
  environment:
    name: "test-low"
    url: "http://low.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master

test low on demand:
  stage: test
  variables:
    DEPLOYMENT_CONFIGURATION: "skalow"
    MARK: "skalow or common"
    HELM_RELEASE: "test-low-$CI_COMMIT_SHORT_SHA"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    KUBE_NAMESPACE_SDP: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp"
    INGRESS_HOST: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt"
  <<: *test_definition
  after_script:
  - make uninstall
  - kubectl -n $KUBE_NAMESPACE_SDP delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,etcd,configmaps --all
  - make delete_namespace
  - make delete_sdp_namespace
  environment:
    name: "test-low"
    url: "http://ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: "ci-test-low-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
  when: manual
  only:
    refs:
      - branches

.sdp_config_dump_template: &sdp_config_dump_definition
  tags:
  - docker-executor
  script:
  - kubectl exec -n $KUBE_NAMESPACE sdp-console-0 -- sdpcfg ls values -R / > sdp.config.json
  when: manual
  artifacts:
    paths:
    - sdp.config.json

sdp_config_dump_mid:
  stage: debug
  variables:
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
  environment:
    name: "test"
    url: "http://mid.integration.engageska-portugal.pt/testdb"
    kubernetes:
      namespace: $KUBE_NAMESPACE
  only:
    refs:
      - master
  <<: *sdp_config_dump_definition

xray_report:
  stage: post_test
  tags:
  - docker-executor
  script:
    - 'curl -X POST -H "Content-type: application/json" --fail
         -H "Authorization: Basic $JIRA_AUTH"
         --data @build/cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  when: always
  only: [master]
  retry: 2
