elastic:
  enabled: false
fluentd:
  enabled: false
kibana:
  enabled: false
tests:
  enabled: false
hdbppdb:
  enabled: true
archiver:
  enabled: false
tangodb:
  use_pv: false
tangotest:
  enabled: true
webjive:
  enabled: false

minikube: true
