
imageToTest: nexus.engageska-portugal.pt/ska-docker/tango-vscode:0.2.4
kubeNamespace: integration
helmRelease: test
pythonPath: "/home/tango/skampi/:/home/tango/skampi/post-deployment/:"
sshPort: 30022
httpPort: 30080
hostPath: /home/ubuntu/skampi
hostName: dev-testing.engageska-portugal.pt
serviceAccount: testing-pod
webPytest:
    enabled: False
testingContainer:
    cpuRequirement:
        request: 600m  # 600m = 0.6 CPU
        limit: 900m 
    memoryRequirement:
        request: 1100Mi
        limit: 1200Mi
webPyTestContainer:
    cpuRequirement:
        request: 600m  # 600m = 0.6 CPU
        limit: 700m 
    memoryRequirement:
        request: 500Mi
        limit: 600Mi



