{{ if .Values.centralnode.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: centralnode-{{ template "integration-tmc-webui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: centralnode-{{ template "integration-tmc-webui.name" . }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: rsyslog-{{ template "integration-tmc-webui.name" . }}
  containers:
  - name: centralnode
    image: "{{ .Values.centralnode.image.registry }}/{{ .Values.centralnode.image.image }}:{{ .Values.centralnode.image.tag }}"
    imagePullPolicy: {{ .Values.centralnode.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "/usr/local/bin/wait-for-it.sh databaseds-{{ template "integration-tmc-webui.name" . }}:10000 --timeout=30 --strict --
             tango_admin --add-server CentralNode/test CentralNode ska_mid/tm_central/central_node &&\
             sudo ln -sf /logs/log /dev/log &&\
             tango_admin --check-device mid_d0001/elt/master &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --check-device ska_mid/tm_leaf_node/d0001 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --check-device ska_mid/tm_subarray_node/1 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/1 10 &&\
             tango_admin --check-device ska_mid/tm_subarray_node/2 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/2 10 &&\
             /venv/bin/python /app/tmcprototype/CentralNode/CentralNode/CentralNode.py test"
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}:10000


{{- with .Values.centralnode.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}