{{ if .Values.dishmaster.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: dishmaster-{{ template "integration-tmc-webui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dishmaster-{{ template "integration-tmc-webui.name" . }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: rsyslog-{{ template "integration-tmc-webui.name" . }}
  
  containers:
  - name: dishmaster
    image: "{{ .Values.dishmaster.image.registry }}/{{ .Values.dishmaster.image.image }}:{{ .Values.dishmaster.image.tag }}"
    imagePullPolicy: {{ .Values.dishmaster.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "/usr/local/bin/wait-for-it.sh databaseds-{{ template "integration-tmc-webui.name" . }}:10000 --timeout=30 --strict --
             tango_admin --add-server DishMaster/test DishMaster mid_d0001/elt/master &&\
             sudo ln -sf /logs/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py test"
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}:10000

{{- with .Values.dishmaster.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}