{{ if .Values.webjive.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
  selector:
    app: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  serviceName: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
        chart: {{ template "integration-tmc-webui.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.image }}:{{ .Values.mongodb.image.tag }}"
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - name: mongodb
          containerPort: 27017
          protocol: TCP
        volumeMounts:
        - name: mongodbdata
          mountPath: /data/db

        resources:
{{ toYaml .Values.rsyslog.resources | indent 10 }}
      volumes:
      - name: mongodbdata
        persistentVolumeClaim:
          claimName: mongodb-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}