{{ if .Values.subarraynode.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: subarraynode-{{ template "integration-tmc-webui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: subarraynode-{{ template "integration-tmc-webui.name" . }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: rsyslog-{{ template "integration-tmc-webui.name" . }}
  containers:
  - name: subarraynode
    image: "{{ .Values.subarraynode.image.registry }}/{{ .Values.subarraynode.image.image }}:{{ .Values.subarraynode.image.tag }}"
    imagePullPolicy: {{ .Values.subarraynode.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "/usr/local/bin/wait-for-it.sh databaseds-{{ template "integration-tmc-webui.name" . }}:10000 --timeout=30 --strict --
             tango_admin --add-server SubarrayNode/test1 SubarrayNode ska_mid/tm_subarray_node/1 &&\
             tango_admin --add-property ska_mid/tm_subarray_node/1 DishLeafNodePrefix ska_mid/tm_leaf_node/d &&\
             tango_admin --add-server SubarrayNode/test2 SubarrayNode ska_mid/tm_subarray_node/2 &&\
             tango_admin --add-property ska_mid/tm_subarray_node/2 DishLeafNodePrefix ska_mid/tm_leaf_node/d &&\
             sudo ln -sf /logs/log /dev/log &&\
             tango_admin --check-device mid_d0001/elt/master &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --check-device ska_mid/tm_leaf_node/d0001 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py test1 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py test2"
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}:10000

{{- with .Values.subarraynode.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}