{{ if .Values.webjive.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: webjive-http
    port: 80
    protocol: TCP
  - name: tangogql-tcp
    port: 5004
    targetPort: tangogql-tcp
    protocol: TCP
  - name: dashboards-tcp
    port: 3012
    protocol: TCP
  - name: authserver-tcp
    port: 8080
    protocol: TCP
  - name: mongodb
    port: 27017
    protocol: TCP
  selector:
    app: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webjive-tangogql-nw-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/app-root: /graphiql
spec:
  rules:
    - http:
        paths:
        - path: /testdb/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 5004
        - path: /testdb/db/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 5004
        - path: /testdb/graphiql/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 5004
        - path: /testdb/socket/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 5004

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        - path: /(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 80
        - path: /testdb/dashboard
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 80
        - path: /testdb/dashboard/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 80
        - path: /dashboards/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 3012
        - path: /auth/(.*)
          backend:
           serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
           servicePort: 8080



---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  serviceName: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: webjive-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
        chart: {{ template "integration-tmc-webui.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      initContainers:
      - name: waitdatabaseds
        image: nexus.engageska-portugal.pt/ska-docker/tango-itango:latest
        imagePullPolicy: IfNotPresent
        command:
          - /usr/local/bin/wait-for-it.sh
          - databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000
          - --timeout=30
          - --strict
          - --
          - echo "Databaseds ready for use."

      containers:
      - name: webjive
        image: "{{ .Values.webjive.image.registry }}/{{ .Values.webjive.image.image }}:{{ .Values.webjive.image.tag }}"
        imagePullPolicy: {{ .Values.webjive.image.pullPolicy }}
        ports:
        - name: webjive-http
          containerPort: 80
          protocol: TCP

      - name: authserver
        image: "{{ .Values.authserver.image.registry }}/{{ .Values.authserver.image.image }}:{{ .Values.authserver.image.tag }}"
        imagePullPolicy: {{ .Values.authserver.image.pullPolicy }}
        ports:
        - name: authserver-tcp
          containerPort: 8080
          protocol: TCP
        env:
          - name: SECRET
            value: "s3cr3t"

      - name: dashboards
        image: "{{ .Values.dashboards.image.registry }}/{{ .Values.dashboards.image.image }}:{{ .Values.dashboards.image.tag }}"
        imagePullPolicy: {{ .Values.dashboards.image.pullPolicy }}
        env:
          - name: MONGO_HOST
            value: "mongodb://localhost/dashboards"
          - name: SECRET
            value: "s3cr3t"
        ports:
        - name: dashboards-tcp
          containerPort: 3012
          protocol: TCP

      - name: tangogql
        image: "{{ .Values.tangogql.image.registry }}/{{ .Values.tangogql.image.image }}:{{ .Values.tangogql.image.tag }}"
        imagePullPolicy: {{ .Values.tangogql.image.pullPolicy }}
        volumeMounts:
        - mountPath: /var/log/tangogql
          name: tangogql-logs
        env:
          - name: LOG_PATH
            value: "/var/log/tangogql"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: TANGO_HOST
            value: databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000
        ports:
        - name: tangogql-tcp
          containerPort: 5004
          protocol: TCP

      - name: redis
        image: "{{ .Values.redis.image.image }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - name: redis-tcp
          containerPort: 6379
          protocol: TCP

      - name: mongodb
        image: "{{ .Values.mongodb.image.image }}:{{ .Values.mongodb.image.tag }}"
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - name: mongodb
          containerPort: 27017
          protocol: TCP

        resources:
{{ toYaml .Values.webjive.resources | indent 10 }}
      volumes:
      - name: tangogql-logs
        persistentVolumeClaim:
          claimName: rsyslog-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}
