{{ if .Values.databaseds.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "tango-base.dbservice-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: production
spec:
  ports:
  - name: ds
    port: 10000
  type: NodePort
  selector:
    app: {{ template "tango-base.name" . }}
    component: {{ .Values.databaseds.component }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tango-base.dbservice-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.databaseds.component }}
    function: {{ .Values.databaseds.function }}
    domain: {{ .Values.databaseds.domain }}
    intent: production
spec:
  selector:
    matchLabels:
      app: {{ template "tango-base.name" . }}
      component: {{ .Values.databaseds.component }}
  serviceName: databaseds-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "tango-base.labels" . | indent 8 }}
        component: {{ .Values.databaseds.component }}
        function: {{ .Values.databaseds.function }}
        domain: {{ .Values.databaseds.domain }}
        intent: production
    spec:
      containers:
      - name: databaseds
        image: "{{ .Values.databaseds.image.registry }}/{{ .Values.databaseds.image.image }}:{{ .Values.databaseds.image.tag }}"
        imagePullPolicy: {{ .Values.databaseds.image.pullPolicy }}
        command:
          - /usr/local/bin/wait-for-it.sh
          - tangodb-{{ template "tango-base.name" . }}-{{ .Release.Name }}:3306
          - --timeout=30
          - --strict
          - --
          - /usr/local/bin/DataBaseds
          - "2"
          - -ORBendPoint
          - giop:tcp::10000
        env:
          - name: MYSQL_HOST
            value: tangodb-{{ template "tango-base.name" . }}-{{ .Release.Name }}:3306
          - name: MYSQL_DATABASE
            value: "{{ .Values.tangodb.db.db }}"
          - name: MYSQL_USER
            value: "{{ .Values.tangodb.db.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.tangodb.db.password }}"
          - name: TANGO_HOST
            value: databaseds-{{ template "tango-base.name" . }}-{{ .Release.Name }}:10000
        ports:
        - name: ds
          containerPort: 10000
        resources:
{{ toYaml .Values.databaseds.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}
