{{ if .Values.tangotest.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: tangotest-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tangotest-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: tangotest
    image: "{{ .Values.tangotest.image.registry }}/{{ .Values.tangotest.image.image }}:{{ .Values.tangotest.image.tag }}"
    imagePullPolicy: {{ .Values.tangotest.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - "{{- if .Values.tangoDatabaseDS }}{{ .Values.tangoDatabaseDS }}{{- else -}}{{ if .Values.databaseds.domainTag }}databaseds-{{ template "tango-base.name" . }}-{{ .Values.databaseds.domainTag }}{{- else }}databaseds-{{ template "tango-base.name" . }}-{{ .Release.Name }}{{- end }}{{- end }}:10000"
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/TangoTest
      - test
    env:
    - name: TANGO_HOST
      value: "{{- if .Values.tangoDatabaseDS }}{{ .Values.tangoDatabaseDS }}{{- else -}}{{ if .Values.databaseds.domainTag }}databaseds-{{ template "tango-base.name" . }}-{{ .Values.databaseds.domainTag }}{{- else }}databaseds-{{ template "tango-base.name" . }}-{{ .Release.Name }}{{- end }}{{- end }}:10000"
    resources:
{{ toYaml .Values.tangotest.resources | indent 6 }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}