---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["roles", "clusterroles", "clusterrolebindings", "customresourcedefinitions"]
  verbs: ["*"]