{{ if .Values.rbac.enabled }}

{{ range .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .name }} # a Role is valid per namespace
  name: {{ .name }}-role
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["*"] # all resources
  verbs: ["*"] # all verbs

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "matteo" to work in the "{{ .name }}" namespace.
kind: RoleBinding
metadata:
  name: {{ .name }}-binding
  namespace: {{ .name }}
subjects:
{{ range .users }}
- kind: User
  name: {{ . }} # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
{{ end }}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ .name }}-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

{{ end }}
{{ end }}
