{{ if .Values.rbac.enabled }}

{{ range .Values.namespaces }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users-cluster-role-binding
subjects:
{{ range .users }}
- kind: User
  name: {{ . }} 
  apiGroup: rbac.authorization.k8s.io
{{ end }}
roleRef:
  kind: ClusterRole 
  name: auth-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users-pv-provisioner-binding
subjects:
{{ range .users }}
- kind: User
  name: {{ . }} 
  apiGroup: rbac.authorization.k8s.io
{{ end }}
roleRef:
  kind: ClusterRole 
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io

{{ end }}
{{ end }}
