{{ if .Values.vscode.enabled }}
---

---
apiVersion: v1
kind: Pod
metadata:
  name: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: vscode
    image: "{{ .Values.vscode.image.registry }}/{{ .Values.vscode.image.image }}:{{ .Values.vscode.image.tag }}"
    imagePullPolicy: {{ .Values.vscode.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "/usr/bin/code --user-data-dir=/root && sleep infinity"
    env:
    - name: XAUTHORITY
      value: "/tmp/.Xauthority"
    - name: DISPLAY
      value: "{{ .Values.display }}"
    - name: TANGO_HOST
      value: databaseds-{{ template "tango-base.name" . }}-{{ .Release.Name }}:10000
    volumeMounts:
      - name: xauthority
        mountPath: /tmp/.Xauthority
        readOnly: true
      - name: data
        mountPath: /usr/src/
  volumes:
  - hostPath:
      path: {{ .Values.xauthority }}
      type: File
    name: xauthority
  - hostPath:
      path: /usr/src/
    name: data
  restartPolicy: Never
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}