{{ if .Values.vscode.enabled }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-{{ template "tango-base.name" . }}-authorized-keys-configuration-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  authorized_keys:
{{ (tpl (.Files.Glob "data/authorized_keys").AsConfig . ) | indent 2 }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-{{ template "tango-base.name" . }}-settings-json-configuration-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  settings.json:
{{ (tpl (.Files.Glob "data/settings.json").AsConfig . ) | indent 2 }}
---

apiVersion: v1
kind: Service
metadata:
  name: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: 2022
    targetPort: 22
    protocol: TCP
  selector:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  serviceName: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
        chart: {{ template "tango-base.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      volumes:
      - name: authorized_keys
        configMap:
          name: "vscode-{{ template "tango-base.name" . }}-authorized-keys-configuration-{{ .Release.Name }}"
      - name: settings_json
        configMap:
          name: "vscode-{{ template "tango-base.name" . }}-settings-json-configuration-{{ .Release.Name }}"
      
      containers:
      - name: vscode
        image: "{{ .Values.vscode.image.registry }}/{{ .Values.vscode.image.image }}:{{ .Values.vscode.image.tag }}"
        imagePullPolicy: {{ .Values.vscode.image.pullPolicy }}
        ports:
        - containerPort: 22
        volumeMounts:
        - name: authorized_keys 
          mountPath: ~/.ssh
        - name: authorized_keys 
          mountPath: ~/.vscode
        resources:
{{ toYaml .Values.vscode.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}