apiVersion: v2
name: mvp-mid
description: A Helm chart for Kubernetes MVP Mid
type: application
version: 0.2.0
appVersion: 0.2.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-base
  version: 0.2.12
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tango-util
  version: 0.2.8
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
#- name: etcd-operator
#  version: 0.11.0
#  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: mid-cbf
  version: 0.1.1
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: mid-cbf.enabled
- name: mid-csp
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: mid-csp.enabled
- name: sdp
  version: 0.2.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: sdp.enabled
- name: tmc-mid
  version: 0.1.3
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: tmc-mid.enabled
- name: oet-scripts
  version: 0.3.1
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: oet.enabled
- name: webjive
  version: 1.0.9
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: webjive.enabled
- name: archiver
  version: 0.2.10
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: archiver.enabled
- name: skuid
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: skuid.enabled
## it was disabled in the old version of skampi
# - name: dsh-lmc-prototype
#   version: 0.0.1
#   repository: https://nexus.engageska-portugal.pt/repository/helm-chart
