display: ":0"
xauthority: "~/.Xauthority"

global:
  sub-system:
    tango-util:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

landingpage:
  enabled: true
  MVPInstance: mvp-mid

skuid:
  enabled: true
  skuid:
    use_pv: false

tango-base:
  enabled: true
  vnc:
    enabled: true
  tangorest:
    enabled: true
  tangotest:
    enabled: true
  ingress:
    enabled: true
    hostname: integration.engageska-portugal.pt
  tangodb:
    use_pv: false

webjive:
  enabled: true
  minikube: false
  ingress:
    enabled: true
    nginx: true
    hostname: integration.engageska-portugal.pt

oet-scripts:
  enabled: true
  ingress:
    hostname: integration.engageska-portugal.pt
  system: TM-mid
  telescope: SKA-mid
  central_node: ska_mid/tm_central/central_node
  subarray: ska_mid/tm_subarray_node
  jupyter:
    featureFlags:
      readViaPubSub: false
  rest:
    featureFlags:
      readViaPubSub: false


#telescope control
## mid-cbf
mid-cbf:
  enabled: true

## mid-csp
mid-csp:
  enabled: true
    
## sdp
sdp:
  enabled: true

## tm
tmc-mid:
  enabled: true
  deviceServers:
  - name: dishmaster1
    function: receptor-simulation
    domain: sensing
    command: "/usr/local/bin/DishMasterDS "
    instances: ["01"]
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishmaster2
    function: receptor-simulation
    domain: sensing
    command: "/usr/local/bin/DishMasterDS "
    instances: ["02"]
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishmaster3
    function: receptor-simulation
    domain: sensing
    command: "/usr/local/bin/DishMasterDS "
    instances: ["03"]
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishmaster4
    function: receptor-simulation
    domain: sensing
    command: "/usr/local/bin/DishMasterDS "
    instances: ["04"]
    depends_on:
      - device: sys/database/2
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishleafnode1
    function: dish-monitoring
    domain: general-monitoring
    command: "/usr/local/bin/DishLeafNodeDS"
    instances: ["01"]
    depends_on:
      - device: mid_d0001/elt/master
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishleafnode2
    function: dish-monitoring
    domain: general-monitoring
    command: "/usr/local/bin/DishLeafNodeDS"
    instances: ["02"]
    depends_on:
      - device: mid_d0002/elt/master
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishleafnode3
    function: dish-monitoring
    domain: general-monitoring
    command: "/usr/local/bin/DishLeafNodeDS"
    instances: ["03"]
    depends_on:
      - device: mid_d0003/elt/master
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: dishleafnode4
    function: dish-monitoring
    domain: general-monitoring
    command: "/usr/local/bin/DishLeafNodeDS"
    instances: ["04"]
    depends_on:
      - device: mid_d0004/elt/master
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: cspsubarrayleafnode1
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/CspSubarrayLeafNodeDS"
    instances: ["01"]
    depends_on:
      - device: mid_csp/elt/subarray_01
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: cspsubarrayleafnode2
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/CspSubarrayLeafNodeDS"
    instances: ["02"]
    depends_on:
      - device: mid_csp/elt/subarray_02
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: cspsubarrayleafnode3
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/CspSubarrayLeafNodeDS"
    instances: ["03"]
    depends_on:
      - device: mid_csp/elt/subarray_03
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: cspmasterleafnode
    function: csp-monitoring
    domain: general-monitoring
    command: "/usr/local/bin/CspMasterLeafNodeDS"
    instances: ["01"]
    depends_on:
      - device: mid_csp/elt/master
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: sdpsubarrayleafnode1
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SdpSubarrayLeafNodeDS"
    instances: ["01"]
    depends_on:
      - device: mid_sdp/elt/subarray_1
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: sdpsubarrayleafnode2
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SdpSubarrayLeafNodeDS"
    instances: ["02"]
    depends_on:
      - device: mid_sdp/elt/subarray_2
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: sdpsubarrayleafnode3
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SdpSubarrayLeafNodeDS"
    instances: ["03"]
    depends_on:
      - device: mid_sdp/elt/subarray_3
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: sdpmasterleafnode
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SdpMasterLeafNodeDS"
    instances: ["01"]
    depends_on:
      - device: mid_sdp/elt/master
    image:
      registry: "{{.Values.tmcprototype.image.registry}}"
      image: "{{.Values.tmcprototype.image.image}}"
      tag: "{{.Values.tmcprototype.image.tag}}"
      pullPolicy: "{{.Values.tmcprototype.image.pullPolicy}}"
  - name: subarraynode1
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SubarrayNodeDS"
    instances: ["sa1"]
    depends_on:
      - device: ska_mid/tm_leaf_node/csp_subarray01
      - device: ska_mid/tm_leaf_node/sdp_subarray01
    image:
      registry: "{{.Values.subarraynodemid.image.registry}}"
      image: "{{.Values.subarraynodemid.image.image}}"
      tag: "{{.Values.subarraynodemid.image.tag}}"
      pullPolicy: "{{.Values.subarraynodemid.image.pullPolicy}}"
  - name: subarraynode2
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SubarrayNodeDS"
    instances: ["sa2"]
    depends_on:
      - device: ska_mid/tm_leaf_node/csp_subarray02
      - device: ska_mid/tm_leaf_node/sdp_subarray02
    image:
      registry: "{{.Values.subarraynodemid.image.registry}}"
      image: "{{.Values.subarraynodemid.image.image}}"
      tag: "{{.Values.subarraynodemid.image.tag}}"
      pullPolicy: "{{.Values.subarraynodemid.image.pullPolicy}}"
  - name: subarraynode3
    function: observation-execution
    domain: subarray
    command: "/usr/local/bin/SubarrayNodeDS"
    instances: ["sa3"]
    depends_on:
      - device: ska_mid/tm_leaf_node/csp_subarray03
      - device: ska_mid/tm_leaf_node/sdp_subarray03
    image:
      registry: "{{.Values.subarraynodemid.image.registry}}"
      image: "{{.Values.subarraynodemid.image.image}}"
      tag: "{{.Values.subarraynodemid.image.tag}}"
      pullPolicy: "{{.Values.subarraynodemid.image.pullPolicy}}"
  - name: centralnode
    function: telescope-monitoring
    domain: general-monitoring
    command: "/usr/local/bin/CentralNodeDS"
    instances: ["01"]
    resources:
      limits:
        cpu: 900m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 128Mi
    depends_on:
      - device: ska_mid/tm_leaf_node/csp_master
      - device: ska_mid/tm_leaf_node/sdp_master
      - device: ska_mid/tm_subarray_node/1
      - device: ska_mid/tm_subarray_node/2
      - device: ska_mid/tm_subarray_node/3
    image:
      registry: "{{.Values.centralnodemid.image.registry}}"
      image: "{{.Values.centralnodemid.image.image}}"
      tag: "{{.Values.centralnodemid.image.tag}}"
      pullPolicy: "{{.Values.centralnodemid.image.pullPolicy}}"
  - name: tm-alarmhandler
    function: alarm-management
    domain: general-monitoring
    command: "./app/alarmhandler-srv"
    instances: ["01"]
    depends_on:
      - device: sys/database/2
    image:
      registry: nexus.engageska-portugal.pt/tango-example
      image: tmalarmhandler
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 128Mi
