display: ":0"
xauthority: "~/.Xauthority"

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    tango-util:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

landingpage:
  enabled: true
  MVPInstance: mvp-mid

skuid:
  enabled: true
  skuid:
    use_pv: false

tango-base:
  enabled: true
  vnc:
    enabled: true
  tangorest:
    enabled: true
  tangodb:
    use_pv: false

webjive:
  enabled: true
  minikube: false
  ingress:
    enabled: true
    nginx: true
    hostname: integration.engageska-portugal.pt

oet-scripts:
  enabled: true
  ingress:
    hostname: integration.engageska-portugal.pt
  system: TM-mid
  telescope: SKA-mid
  central_node: ska_mid/tm_central/central_node
  subarray: ska_mid/tm_subarray_node
  jupyter:
    featureFlags:
      readViaPubSub: false
  rest:
    featureFlags:
      readViaPubSub: false


#telescope control
## mid-cbf
mid-cbf:
  enabled: true

## mid-csp
mid-csp:
  enabled: true

## sdp
sdp:
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  tango-base:
    enabled: false

## tm
tmc-mid:
  enabled: true



