
display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  sub-system:

tango-base:
  vnc:
    enabled: true
  tangorest:
    enabled: true
    resources:
      requests:
        cpu: 100m     # 100m = 0.1 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m     # 100m = 0.1 CPU
        memory: 768Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
  tangodb:
    use_pv: false

logging:
  elastic:
    enabled: false
  fluentd:
    enabled: false
  kibana:
    enabled: false
  tests:
    enabled: false

archiver:
  hdbppdb:
    enabled: true
  archiver:
    enabled: true

webjive:
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt
    
etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false