
display: ":0"
xauthority: "~/.Xauthority"

global:
  sub-system:
    tango-util:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: false
    archiver:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

skuid:
  enabled: true
  use_pv: false

tango-base:
  enabled: true
  vnc:
    enabled: true
  tangorest:
    enabled: true
    resources:
      requests:
        cpu: 100m     # 100m = 0.1 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m     # 100m = 0.1 CPU
        memory: 512Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
    hostname: integration.engageska-portugal.pt
  tangodb:
    use_pv: false

archiver:
  enabled: true
  attributes2archive:
  - attributes:
    - "mid_d0001/elt/master/WindSpeed"
    - "mid_d0001/elt/master/achievedPointing"
    - "mid_d0001/elt/master/desiredPointing"
    - "mid_d0002/elt/master/WindSpeed"
    - "mid_d0002/elt/master/achievedPointing"
    - "mid_d0002/elt/master/desiredPointing"
    - "mid_d0003/elt/master/WindSpeed"
    - "mid_d0003/elt/master/achievedPointing"
    - "mid_d0003/elt/master/desiredPointing"
    - "mid_d0004/elt/master/WindSpeed"
    - "mid_d0004/elt/master/achievedPointing"
    - "mid_d0004/elt/master/desiredPointing"
    - "sys/tg_test/1/ulong_scalar"
    - "sys/tg_test/1/long64_scalar"
    - "sys/tg_test/1/long_scalar"
    polling_period: 1000
    period_event: 3000
  - attributes:
    - "mid_csp/elt/subarray_01/State"
    - "mid_csp/elt/subarray_01/obsState"
    - "mid_d0001/elt/master/State"
    - "mid_d0001/elt/master/pointingState"
    - "mid_d0002/elt/master/State"
    - "mid_d0002/elt/master/pointingState"
    - "mid_sdp/elt/subarray_1/obsState"
    - "mid_sdp/elt/subarray_1/State"
    - "ska_mid/tm_subarray_node/1/State"
    - "ska_mid/tm_subarray_node/1/obsState"
    polling_period: 100
    period_event: 300

webjive:
  enabled: true
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false


#telescope control
## mid-cbf
mid-cbf:
  enabled: true

## mid-csp
mid-csp:
  enabled: true
    
## sdp
sdp:
  enabled: true

## tm
tmc-mid:
  enabled: true

## oet
oet:
  enabled: true




