display: ":0"
xauthority: "~/.Xauthority"

global:
  retry:
    - "--sleep=1"
    - "--tries=100"
  sub-system:
    tango-util:
      enabled: false
    tango-base:
      enabled: false
    webjive:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

ska-archiver:
  hostname: 192.168.99.229
  dbname: default_mvp_archiver_db
  port: 3306
  dbuser: eda_admin
  dbpassword: "@v3ng3rs@ss3mbl3"
  enabled: false

landingpage:
  enabled: true
  MVPInstance: mvp-mid

skuid:
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01

tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

webjive:
  enabled: false
  minikube: false
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 3
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

oet-scripts:
  enabled: true
  ingress:
    hostname: k8s.stfc.skao.int
  system: TM-mid
  telescope: SKA-mid
  central_node: ska_mid/tm_central/central_node
  subarray: ska_mid/tm_subarray_node
  jupyter:
    featureFlags:
      readViaPubSub: false
  rest:
    featureFlags:
      readViaPubSub: false

#telescope control
## mid-cbf
mid-cbf:
  enabled: true

## mid-csp
mid-csp:
  enabled: true

## sdp
sdp:
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  tango-base:
    enabled: false

## tm
tmc-mid:
  enabled: true
