
display: ":0"
xauthority: "~/.Xauthority"
minikube: false

global:
  sub-system:
    tango-base:
      enabled: false
    webjive:
      enabled: false
    archiver:
      enabled: false
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

tango-base:
  vnc:
    enabled: true
  tangorest:
    enabled: true
    resources:
      requests:
        cpu: 100m     # 100m = 0.1 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m     # 100m = 0.1 CPU
        memory: 768Mi # 256Mi = 0.25 GB mem
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
  tangodb:
    use_pv: false

logging:
  elastic:
    enabled: false
  fluentd:
    enabled: false
  kibana:
    enabled: false
  tests:
    enabled: false

archiver:
  hdbppdb:
    enabled: true
  archiver:
    enabled: true

webjive:
  minikube: false
  ingress:
    enabled: true
    nginx: false
    hostname: integration.engageska-portugal.pt

etcd-operator:
  deployments:
    backupOperator: false
    restoreOperator: false
