# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


elastic:
  enabled: true
  image:
    registry: docker.elastic.co
    image: elasticsearch/elasticsearch
    tag: 6.5.4
    pullPolicy: IfNotPresent

fluentd:
  enabled: true
  image:
    image: fluent/fluentd-kubernetes-daemonset
    tag: v1-debian-syslog
    pullPolicy: IfNotPresent
  livenessProbe:
    enabled: true

kibana:
  enabled: true
  image:
    registry: docker.elastic.co
    image: kibana/kibana
    tag: 6.5.4
    pullPolicy: IfNotPresent
  basePath: /kibana

ingress:
  enabled: true
  nginx: true
  hostname: integration.engageska-portugal.pt

logstash:
  enabled: true
  hostname: integration.engageska-portugal.pt
