apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: {{ .Values.sdp.helmdeploy.namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: local-pvc-job
  namespace: {{ .Values.sdp.helmdeploy.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: local-pvc-job-pod
          image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:1.5.0
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "mkdir /mnt/data; curl https://gitlab.com/ska-telescope/cbf-sdp-emulator/-/raw/master/data/sim-vis.ms.tar.gz | tar xzf - -C /mnt/data" ]
          volumeMounts:
            - mountPath: "/mnt"
              name: task-pv
      volumes:
      - name: task-pv
        persistentVolumeClaim:
          claimName: local-pvc
