---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 128Mi
      cpu: 100m
      ephemeral-storage: 100Mi
    defaultRequest:
      memory: 128Mi
      cpu: 100m
      ephemeral-storage: 100Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "250"
    requests.cpu: 32000m
    requests.memory: 32Gi
    requests.ephemeral-storage: 15Gi
    limits.cpu: 32000m
    limits.memory: 32Gi
    limits.ephemeral-storage: 20Gi
