---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 0.5
    defaultRequest:
      memory: 128Mi
      cpu: 0.25
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "50"
    requests.cpu: 4000m
    requests.memory: 4Gi
    requests.ephemeral-storage: 20Gi
    limits.cpu: 8000m
    limits.memory: 16Gi
    limits.ephemeral-storage: 40Gi

# tango-base pods: 11
# tango-base request cpu total: 1300m
# tango-base request mem total: 2396Mi
# tango-base request ephemeral-storage total: 4768Mi
# tango-base limits  cpu total: 2000m
# tango-base limits  mem total: 3128Mi
# tango-base limits ephemeral-storage total: 6256Mi
