---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 128Mi
      cpu: 100m
      ephemeral-storage: 100Mi
    defaultRequest:
      memory: 128Mi
      cpu: 100m
      ephemeral-storage: 100Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "250"
    requests.cpu: 16000m
    requests.memory: 16Gi
    requests.ephemeral-storage: 15Gi
    limits.cpu: 16000m
    limits.memory: 16Gi
    limits.ephemeral-storage: 20Gi

# tango-base pods: 11
# tango-base request cpu total: 1300m
# tango-base request mem total: 2396Mi
# tango-base request ephemeral-storage total: 4768Mi
# tango-base limits  cpu total: 2000m
# tango-base limits  mem total: 3128Mi
# tango-base limits ephemeral-storage total: 6256Mi
