apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ include "sdp-prototype.name" . }}-etcd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.etcd.component }}
    subsystem: {{ .Values.etcd.subsystem }}
    function: {{ .Values.etcd.function }}
    domain: {{ .Values.etcd.domain }}
    intent: production
spec:
  size: {{ .Values.etcd.replicas }}
  version: "{{ .Values.etcd.version }}"
  pod:
    antiAffinity: false
    nodeSelector: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp-prototype.name" . }}-etcd-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.etcd.component }}
    subsystem: {{ .Values.etcd.subsystem }}
    function: {{ .Values.etcd.function }}
    domain: {{ .Values.etcd.domain }}
    intent: production
spec:
  type: NodePort
  selector:
    etcd_cluster: {{ include "sdp-prototype.name" . }}-etcd
    app: etcd
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
