# giving a dummy Service entry ensures that the single pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
spec:
  clusterIP: None
  ports:
  - name: dummy # Actually, no port is needed.
    port: 1234
    targetPort: 1234
  selector:
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
spec:
  replicas: {{ .Values.helm_deploy.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.helm_deploy.component }}
      subsystem: {{ .Values.helm_deploy.subsystem }}
  serviceName: {{ include "sdp-prototype.name" . }}-helm-deploy
  template:
    metadata:
      labels:
        {{- include "sdp-prototype.labels" . | indent 8 }}
        component: {{ .Values.helm_deploy.component }}
        subsystem: {{ .Values.helm_deploy.subsystem }}
        function: {{ .Values.helm_deploy.function }}
        domain: {{ .Values.helm_deploy.domain }}
        intent: production
    spec:
      initContainers:
      {{ include "sdp-prototype.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.helm_deploy.image }}:{{ .Values.helm_deploy.version }}
        imagePullPolicy: {{ .Values.helm_deploy.imagePullPolicy }}
        name: helm-deploy
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helm_deploy.namespace }}
        - name: SDP_CHART_REPO
          value: "{{ .Values.helm_deploy.chart_repo.url }}"
        - name: SDP_CHART_REPO_REF
          value: "{{ .Values.helm_deploy.chart_repo.ref }}"
        - name: SDP_CHART_REPO_PATH
          value: "{{ .Values.helm_deploy.chart_repo.path }}"
        - name: SDP_CHART_REPO_REFRESH
          value: "{{ .Values.helm_deploy.chart_repo.refresh }}"
      serviceAccountName: {{ include "sdp-prototype.name" . }}-helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm
  namespace: {{ .Values.helm_deploy.namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
subjects:
- kind: ServiceAccount
  name: {{ include "sdp-prototype.name" . }}-helm
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sdp-prototype.name" . }}-helm
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm-global
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
subjects:
- kind: ServiceAccount
  name: {{ include "sdp-prototype.name" . }}-helm
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "sdp-prototype.name" . }}-helm-global
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm
  namespace: {{ .Values.helm_deploy.namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
- apiGroups: ["", "batch", "apps"]
  resources: ["deployments", "jobs", "pods", "configmaps",
              "persistentvolumeclaims", "services", "secrets"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp-prototype.name" . }}-helm-global
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
    component: {{ .Values.helm_deploy.component }}
    subsystem: {{ .Values.helm_deploy.subsystem }}
    function: {{ .Values.helm_deploy.function }}
    domain: {{ .Values.helm_deploy.domain }}
    intent: production
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
