{{ if .Values.jupyter.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.itango.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.jupyter.component }}
    domain: self-configuration
    function: ingress-configuration
    intent: production
  annotations:
      kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ tpl .Values.ingress.hostname . }}
      http:
        paths:
        - path: /jupyter
          backend:
           serviceName: jupyter-{{ template "oet.name" . }}-{{ .Release.Name }}
           servicePort: 8888
---
apiVersion: v1
data:
  jupyter_notebook_config.json: |-
    {
        "NotebookApp": {
          "password": "sha1:a83c43c88b88:980ac02521dcf9f62f610e26b051f157c05a36fe",
          "base_url": "/jupyter"
        }
    }
kind: ConfigMap
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-notebook-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.jupyter.component }}
    domain: self-configuration
    function: notebook-configuration
    intent: production 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.jupyter.component }}
    function: {{ .Values.jupyter.function }}
    domain: {{ .Values.jupyter.domain }}
    intent: production
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      nodePort: {{ .Values.jupyter.nodePort }}
  selector:
    app: {{ template "oet.name" . }}
    component: {{ .Values.jupyter.component }}
---
{{if .Values.jupyter.storage.enabled}}
{{ if .Values.minikube }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-workspace-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    type: jupyter_storage
    component: {{ .Values.jupyter.component }}
    function: workspace-storage
    domain: storage
    intent: enabling
spec:
  storageClassName: jupyter
  capacity:
    storage: {{ .Values.jupyter.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/jupyter-{{ .Release.Namespace }}-{{ .Release.Name }}/
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-workspace-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    type: jupyter_storage
    function: workspace-storage
    domain: storage
    intent: production
spec:
{{ if .Values.minikube }}
  storageClassName: jupyter
  accessModes:
  - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
  - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: {{ .Values.jupyter.storage.capacity }}
{{end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-env-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.jupyter.component }}
    domain: self-configuration
    function: environmental-settings
    intent: production 
data:
  environment: |
    TANGO_HOST={{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
  venv.sh: |
    export PATH="/venv/bin:${PATH}"
    export OET_REST_URI=http://rest-{{ template "oet.name" . }}-{{ .Release.Name }}:5000/api/v1.0/procedures
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.jupyter.component }}
    function: {{ .Values.jupyter.function }}
    domain: {{ .Values.jupyter.domain }}
    intent: production
spec:
  selector:
    matchLabels:
      app: {{ template "oet.name" . }}
      component: {{ .Values.jupyter.component }}
  serviceName: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "oet.labels" . | indent 8 }}
        component: {{ .Values.jupyter.component }}
        function: {{ .Values.jupyter.function }}
        domain: {{ .Values.jupyter.domain }}
        intent: production
    spec:
      volumes:
        - name: jupyter-configmap-volume
          configMap:
            name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-env-settings
            items:
            - key: environment
              path: environment
            - key: venv.sh
              path: venv.sh
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-workspace-storage
          configMap:
            name: {{ template "oet.name" . }}-{{ .Values.jupyter.component }}-notebook-config
        - name: workdir
          emptyDir: {}
      initContainers:
      - name: check-databaseds-ready
        volumeMounts:
        - name: workdir
          mountPath: /temp
        - name: config
          mountPath: /config
        image: "{{ .Values.jupyter.image.registry }}/{{ .Values.jupyter.image.image }}:{{ .Values.jupyter.image.tag }}"
        command: ["/bin/sh","-c"]
        args: ["/usr/local/bin/wait-for-it.sh {{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }} --timeout=30 --strict -- echo databaseds ready && cp /config/* /temp/"]
      containers:
      - name: oet-jupyter
        image: "{{ .Values.jupyter.image.registry }}/{{ .Values.jupyter.image.image }}:{{ .Values.jupyter.image.tag }}"
        imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
        ports:
          - name: oet-jupyter
            containerPort: 8888
        env:
          - name: TANGO_HOST
            value: {{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
          - name: SHELL
            value: /bin/bash
          - name: OET_REST_URI
            value: http://rest-{{ template "oet.name" . }}-{{ .Release.Name }}:5000/api/v1.0/procedures
          - name: SKUID_URL
            value: "skuid-skuid-{{ .Release.Namespace }}-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:9870"
        volumeMounts:
          - name: storage
            mountPath: /app/jupyter_storage
          - name: workdir
            mountPath: /home/tango/.jupyter
          - name: jupyter-configmap-volume
            mountPath: /etc/environment
            subPath: environment
          - name: jupyter-configmap-volume
            mountPath: /etc/profile.d/venv.sh
            subPath: venv.sh
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: {{ .Values.jupyter.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jupyter.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jupyter.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jupyter.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.jupyter.readinessProbe.failureThreshold }}
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: {{ .Values.jupyter.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.jupyter.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.jupyter.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.jupyter.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.jupyter.livenessProbe.failureThreshold }}
      restartPolicy: Always
      resources:
  {{ toYaml .Values.rest.resources | indent 10 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{ end }}
