# Default values for webjive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"
minikube: true

itango:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi


webjive:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: webjive
    tag: 1.0.301-develop-149
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem

authserver:
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: webjive-auth
    tag: 1.0.0-develop-15
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem

redis:
  image:
    image: redis
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem

mongodb:
  image:
    image: mongo
    tag: 3.6-stretch
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
    limits:
      cpu: 500m     # 500m = 0.5 CPU
      memory: 512Mi # 512Mi = 0.5 GB mem
      ephemeral-storage: 1Gi


dashboards:
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: dashboard-repo
    tag: 1.0.0-develop-11
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem

tangogql:
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: web-maxiv-tangogql
    tag: 1.1.0-develop-19
    pullPolicy: Always
  resources:
    requests:
      cpu: 400m     # 400m = 0.4 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
    limits:
      cpu: 800m     # 800m = 0.8 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

# Configure Ingress resource that allow you to access the Tango REST API
ingress:
  enabled: true
  nginx: false
  hostname: integration.engageska-portugal.pt

  # Ingress annotations
  annotations: {}

  # Ingress TLS configuration
  #
  tls:
    enabled: true
    secretname: "tls-secret-{{ template \"webjive.name\" . }}-{{ .Release.Name }}"
    hostname: "{{ .Values.ingress.hostname }}"


nodeSelector: {}

affinity: {}

tolerations: []
