apiVersion: v2
name: mvp-low
description: A Helm chart for Kubernetes MVP Low
type: application
version: 0.2.3
appVersion: 0.2.3
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-base
  version: 0.2.15
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tango-util
  version: 0.2.9
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tmc-low
  version: 0.1.5
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: ska-low-mccs
  version: 0.4.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: webjive
  version: 1.0.12
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: oet-scripts
  version: 0.3.3
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: oet-scripts.enabled
