
display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  sub-system:
    tango-base:
      enabled: false
    webjive:
      enabled: false
    # archiver:
    #   enabled: false
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

tango-base:
  vnc:
    enabled: true
  tangorest:
    enabled: true
    # resources:
    #   requests:
    #     cpu: 100m     # 100m = 0.1 CPU
    #     memory: 128Mi # 256Mi = 0.25 GB mem
    #     ephemeral-storage: 256Mi
    #   limits:
    #     cpu: 200m     # 100m = 0.1 CPU
    #     memory: 768Mi # 256Mi = 0.25 GB mem
    #     ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
    hostname: integration.engageska-portugal.pt
  tangodb:
    use_pv: false

ska-low-mccs:
  tango-base:
    enabled: false
# mccs:
#   tango-base:
#     enabled: false
#   cli:
#     enabled: false
#   mccs:
#     enabled: true
#   project:
#     name: mccs
#     image:
#       registry: nexus.engageska-portugal.pt/ska-docker
#       image: ska-low-mccs
#       tag: latest
#       pullPolicy: IfNotPresent

webjive:
  minikube: false
  ingress:
    enabled: true
    nginx: true
    hostname: low.integration.engageska-portugal.pt

oet-scripts:
  enabled: true
  ingress:
    hostname: low.integration.engageska-portugal.pt