{{ if .Values.archiver.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "attrconfig-configuration-{{ template "archiver.name" . }}-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data:
  attribute2archive.json:
{{ (tpl (.Files.Glob "data/attribute2archive.json").AsConfig . ) | indent 2 }}
  configure_hdbpp.py:
{{ (tpl (.Files.Glob "data/configure_hdbpp.py").AsConfig . ) | indent 2 }}
  configuration.json: 
{{ (tpl (.Files.Glob "data/configuration.json").AsConfig . ) | indent 2  }}


---
apiVersion: batch/v1
kind: Job
metadata:
  name: attrconfig-{{ template "archiver.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: configureattrconfig
        configMap:
          name: "attrconfig-configuration-{{ template "archiver.name" . }}-{{ .Release.Name }}"
      initContainers:
        - name: wait-for-devices
          image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
          imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
          command:
            - sh
          args:
            - -c
            - "retry --max=20 -- tango_admin --ping-device archiving/hdbpp/eventsubscriber01 && \
              retry --max=20 -- tango_admin --ping-device archiving/hdbpp/confmanager01"
          env:
          - name: TANGO_HOST
            value: databaseds-tango-base-{{ .Release.Name }}:10000
      containers:
      - name: attrconfig
        image: "{{ .Values.attrconfig.image.registry }}/{{ .Values.attrconfig.image.image }}:{{ .Values.attrconfig.image.tag }}"
        imagePullPolicy: {{ .Values.attrconfig.image.pullPolicy }}
        command:
          - sh
        args:
          - -c
          - "/venv/bin/python data/configure_hdbpp.py \ 
              --cm=archiving/hdbpp/confmanager01 \
              --es=archiving/hdbpp/eventsubscriber01 \
              --attrfile=data/attribute2archive.json"
        env:
        - name: TANGO_HOST
          value: databaseds-tango-base-{{ .Release.Name }}:10000
        volumeMounts:
          - name: configureattrconfig
            mountPath: /app/data
            readOnly: true
      restartPolicy: OnFailure


---
apiVersion: batch/v1
kind: Job
metadata:
  name: dsconfig-{{ template "archiver.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: configureattrconfig
        configMap:
          name: "attrconfig-configuration-{{ template "archiver.name" . }}-{{ .Release.Name }}"
      containers:
      - name: dsconfig
        image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
        imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
        command:
        - /usr/local/bin/wait-for-it.sh
        - databaseds-tango-base-{{ .Release.Name }}:10000
        - --timeout=30
        - --strict
        - --
        - json2tango -w -a -u /app/data/configuration.json
        env:
        - name: TANGO_HOST
          value: databaseds-tango-base-{{ .Release.Name }}:10000
        volumeMounts:
          - name: configureattrconfig
            mountPath: /app/data
            readOnly: true
      restartPolicy: OnFailure

{{ end }}

