{{ if .Values.csplmc.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "csp-proto-configuration-json-{{ template "csp-proto.name" . }}-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data: 
  cspconfig.json: 
{{ (tpl (.Files.Glob "data/cspconfig.json").AsConfig . ) | indent 2  }}

---
apiVersion: v1
kind: Pod
metadata:
  name: midcsplmc-{{ template "csp-proto.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: midcsplmc-{{ template "csp-proto.name" . }}-{{ .Release.Name }}
    chart: {{ template "csp-proto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: rsyslog-{{ template "csp-proto.name" . }}-{{ .Release.Name }}
    - name: configuration
      configMap:
        name: "csp-proto-configuration-json-{{ template "csp-proto.name" . }}-{{ .Release.Name }}"

  initContainers:
  - name: dsconfig
    image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
    imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - databaseds-tango-base-{{ .Release.Name }}:10000
      - --timeout=30
      - --strict
      - --
      - json2tango -w -a -u data/cspconfig.json
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000
    volumeMounts:
      - name: configuration
        mountPath: data
        readOnly: true

  containers:
  - name: cspmaster
    image: "{{ .Values.csplmc.image.registry }}/{{ .Values.csplmc.image.image }}:{{ .Values.csplmc.image.tag }}"
    imagePullPolicy: {{ .Values.csplmc.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "sudo ln -sf /logs/log /dev/log && \
            retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
            /venv/bin/python /app/csplmc/CspMaster/CspMaster/CspMaster.py csp"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspsubarray01
    image: "{{ .Values.csplmc.image.registry }}/{{ .Values.csplmc.image.image }}:{{ .Values.csplmc.image.tag }}"
    imagePullPolicy: {{ .Values.csplmc.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "sudo ln -sf /logs/log /dev/log && \
            retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_01 &&\
            /venv/bin/python /app/csplmc/CspSubarray/CspSubarray/CspSubarray.py sub1"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspsubarray02
    image: "{{ .Values.csplmc.image.registry }}/{{ .Values.csplmc.image.image }}:{{ .Values.csplmc.image.tag }}"
    imagePullPolicy: {{ .Values.csplmc.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "sudo ln -sf /logs/log /dev/log && \
            retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_02 &&\
            /venv/bin/python /app/csplmc/CspSubarray/CspSubarray/CspSubarray.py sub2"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspsubarray03
    image: "{{ .Values.csplmc.image.registry }}/{{ .Values.csplmc.image.image }}:{{ .Values.csplmc.image.tag }}"
    imagePullPolicy: {{ .Values.csplmc.image.pullPolicy }}
    volumeMounts:
    - name: logs
      mountPath: /logs
    command:
      - sh
    args:
      - -c
      - "sudo ln -sf /logs/log /dev/log && \
            retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_03 &&\
            /venv/bin/python /app/csplmc/CspSubarray/CspSubarray/CspSubarray.py sub3"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

{{- with .Values.csplmc.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}
