{{ if .Values.jupyter.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-main-ing-{{ template "oet.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
      kubernetes.io/ingress.class: traefik
spec:
{{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ tpl .Values.ingress.hostname . }}
      secretName: {{ tpl .Values.ingress.tls.secretname . }}
{{ end }}
  rules:
    - host: {{ tpl .Values.ingress.hostname . }}
      http:
        paths:
        - path: /oet/jupyter
          backend:
           serviceName: jupyter-{{ template "oet.name" . }}-{{ .Release.Name }}
           servicePort: 80

{{ end }}