apiVersion: v1
kind: Pod
metadata:
 name: oet-ssh
 labels:
  run: ssh
spec:
 initContainers:
  - name: waitdatabaseds
    image: "{{ .Values.oet.image.registry }}/{{ .Values.oet.image.image }}:{{ .Values.oet.image.tag }}"
    imagePullPolicy: Always
    command:
      - /usr/local/bin/wait-for-it.sh
      - databaseds-tango-base-{{ .Release.Name }}:10000
      - --timeout=30
      - --strict
      - --
      - echo "Tango environment is now available"; done;
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000
 containers:
 - name: sshcheck
   image: "{{ .Values.oet.image.registry }}/{{ .Values.oet.image.image }}:{{ .Values.oet.image.tag }}"
   imagePullPolicy: Always
   ports:
    - containerPort: 22
   env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000
 restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: oet-ssh
 labels:
  run: ssh
spec:
 type: NodePort
 ports:
 - port: 2022
   targetPort: 22
   protocol: TCP
 selector:
  run: ssh