{{ if .Values.oet.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
    chart: {{ template "oet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: oet-ssh
    port: 22
    protocol: TCP
  selector:
    app: oet-{{ template "oet.name" . }}-{{ .Release.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
    chart: {{ template "oet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
  serviceName: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
        chart: {{ template "oet.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      initContainers:
      - name: waitdatabaseds
        image: nexus.engageska-portugal.pt/ska-docker/tango-itango:latest
        imagePullPolicy: IfNotPresent
        command:
          - /usr/local/bin/wait-for-it.sh
          - databaseds-tango-base-{{ .Release.Name }}:10000
          - --timeout=30
          - --strict
          - --
          - /usr/local/bin/wait-for-it.sh
          - mongodb-{{ template "oet.name" . }}-{{ .Release.Name }}:27017
          - --timeout=30
          - --strict
          - --
          - echo "Databaseds/Mongodb ready for use."

      containers:
      - name: oet
        image: "{{ .Values.oet.image.registry }}/{{ .Values.oet.image.image }}:{{ .Values.oet.image.tag }}"
        imagePullPolicy: {{ .Values.oet.image.pullPolicy }}
        ports:
        - name: oet-http
          containerPort: 22
          protocol: TCP
        resources:
{{ toYaml .Values.oet.resources | indent 10 }}
      volumes:
      - name: tangogql-logs
        persistentVolumeClaim:
          claimName: oet-{{ template "oet.name" . }}-{{ .Release.Name }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}
