{{ if .Values.oet.enabled }}

---
apiVersion: v1
kind: Service
metadata:
 name: oet-ssh
 labels:
  run: ssh
spec:
 type: NodePort
 ports:
 - port: 2022
   targetPort: 22
   protocol: TCP
 selector:
  run: ssh

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "environment-oet-{{ template "oet.name" . }}-{{ .Release.Name }}"
data:
   environment: |
     TANGO_HOST=databaseds-tango-base-{{ .Release.Name }}:10000
---
apiVersion: v1
kind: Pod
metadata:
 name: oet-ssh
 labels:
  run: ssh
spec:
 volumes:
  - name: environment
    configMap:
      name: "environment-oet-{{ template "oet.name" . }}-{{ .Release.Name }}"
 containers:
 - name: sshcheck
   image: "{{ .Values.oet.image.registry }}/{{ .Values.oet.image.image }}:{{ .Values.oet.image.tag }}"
   imagePullPolicy: Always
   ports:
    - containerPort: 22
   env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000
   volumeMounts:
      - name: environment
        mountPath: /home/tango/.ssh
        readOnly: true
 restartPolicy: Always

{{ end }}