apiVersion: v1
kind: Service
metadata:
  name: event-generating
  labels:
    app: event-generating
spec:
  selector:
    app: event-generating
  clusterIP: None
  ports:
  - name: dummy # Actually, no port is needed.
    port: 1234
    targetPort: 1234

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-generator
  labels:
    app: event-generating
spec:
  selector:
    matchLabels:
      app: event-generating
  serviceName: event-generating
  template:
    metadata:
      labels:
        app: event-generating
    spec:
      volumes:
        - name: git-repo
          emptyDir: {}
      initContainers:
        - name: git-installer
          image: alpine/git
          command:
            - git
          args:
            - clone
            - -b
            - SAR-108-implement-tango-test-device-server
            - https://gitlab.com/ska-telescope/tango-example.git
          volumeMounts:
            - name: git-repo
              mountPath: /git
      containers:
        - name: event-generator
          image: nexus.engageska-portugal.pt/ska-docker/ska-python-runtime:latest
          command:
            - python3
          args:
            - git/tango-example/module_example/TestDevice.py
            - test
          volumeMounts:
            - name: git-repo
              mountPath: /git
          env:
            - name: POD_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TANGO_HOST
              value: databaseds-tango-base-test:10000
    
