# Default values for csp-proto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

system: csp-lmc-mid
telescope: SKA-mid

csplmc:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mid-csp-lmc
    tag: 0.5.9-3f01bac
    pullPolicy: IfNotPresent

deviceServers:
  - name: midcapabilitymonitor
    subsystem: monitoring-system
    function: capability-monitoring
    domain: csp-monitoring
    args:
      - "-c"
      - "/venv/bin/python /app/csp_lmc_mid/MidCspCapabilityMonitor.py monitor"
  - name: midcspmaster
    subsystem: monitoring-system
    function: central-control
    domain: csp-monitoring
    args:
      - "-c"
      - "retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
        retry --max=5 -- tango_admin --ping-device mid_csp/capability_monitor/search_beams &&\
            /venv/bin/python /app/csp_lmc_mid/MidCspMaster.py master"
  - name: midcspsubarray01
    subsystem: subarray1
    function: observation-execution
    domain: subarray
    args:
      - "-c"
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_01 &&\
            /venv/bin/python /app/csp_lmc_mid/MidCspSubarray.py subarray1"
  - name: midcspsubarray02
    subsystem: subarray2
    function: observation-execution
    domain: subarray
    args:
      - "-c"
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_02 &&\
            /venv/bin/python /app/csp_lmc_mid/MidCspSubarray.py subarray2"
  - name: midcspsubarray03
    subsystem: subarray3
    function: observation-execution
    domain: subarray
    args:
      - "-c"
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_03 &&\
            /venv/bin/python /app/csp_lmc_mid/MidCspSubarray.py subarray3"

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.2.5.1
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []

resources: {}
